# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2452e5f7296a6b04f03e6b15ff57a5b3fc3ac68c36cdb4cdf596c9b3f7b6875fc31f2a8ec3a252c3310a848e93fd98fece000fe44c1bc484b128f1e277603988

test:
  secret_key_base: 8d7439701e8bb87dda9ec95becb91563458c1937a39eb0c07135c42ad8db1edc313366499bff00a85df3e008dd9912cdd93bd825ef1be323801a84ee91515bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
